version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: documentation
    versions:
    - 13.1.1
    - 13.2.0
  - dependency-name: tape
    versions:
    - 5.2.1
  - dependency-name: standard-version
    versions:
    - 9.1.0
  - dependency-name: ava
    versions:
    - 3.15.0
