language: node_js
node_js:
  - 'stable'
  - '12'
  - '11'
  - '10'
  - '8'
install:
  - npm ci
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - cat coverage.lcov | coveralls
  - codecov
cache:
  directories:
  - "$HOME/.npm"
