language: node_js
node_js:
  - 'stable'
  - '12'
  - '11'
  - '10'
  - '8'
install:
  - npm ci
after_success:
  - npm ci codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
cache:
  directories:
  - "$HOME/.npm"
