language: node_js
node_js:
  - 'stable'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
after_success:
  yarn add coveralls codecov &&
  nyc report --reporter=text-lcov | coveralls &&
  npm run codecov