language: node_js
node_js:
  - 'stable'
  - '12'
  - '11'
  - '10'
  - '8'
install:
  - npm ci
after_success:
  npx nyc report --reporter=text-lcov > coverage.lcov &&
  cat coverage.lcov | npx coveralls; npx codecov
cache:
  directories:
  - "$HOME/.npm"
